name: RSS Bot

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:      # Allow manual trigger from GitHub UI too

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        run: |
          python rss_bot.py
